server:
   port: 8080

rsa:
   private-key: classpath:certs/private.pem
   public-key: classpath:certs/public.pem  
   
spring:
   servlet:
      multipart:
         max-file-size: 1MB
         max-request-size: 1MB
   mvc:
      pathmatch:
         matching-strategy: ANT_PATH_MATCHER
   datasource:
      url: jdbc:sqlserver://DESKTOP-SLPF06D:1433;databaseName=LTS;encrypt=true;trustServerCertificate=true;
      username: lts_admin
      password: Admin!234
   jpa:
      show-sql: true
      properties:
         hibernate:
            dialect: org.hibernate.dialect.SQLServerDialect          
            format_sql: true
 
org:
   sits:
      pr:
         api:
            thumbnailHeight: 150
            thumbnailWidth: 300
            imageTypesWithMaXWidth: CAROUSEL,IMAGEBAR 
            imageMaxWidthCarousel: 3600
            imageMaxWidth: 1800
            imageMaxHeight: 1200
            expireToken: 2
            downloadURL: http://localhost:8080/image/download/
            downloadThumbnailURL: http://localhost:8080/image/thumbnail/download/
            adminAccess: SCOPE_SYS_ADMIN
            directory:
               uploadedFiles: //Users//vprasath//SynergyITSolutions//Projects//ParkRoyale//UploadedImages//

    